CREATE TABLE endereco (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cep VARCHAR(255),
    logradouro VARCHAR(255),
    numero VARCHAR(255),
    complemento VARCHAR(255),
    bairro VARCHAR(255),
    cidade VARCHAR(255),
    uf VARCHAR(255),
    latitude DOUBLE PRECISION,
    longitude DOUBLE PRECISION,
    data_criacao TIMESTAMP(6),
    data_atualizacao TIMESTAMP(6)
);

CREATE TABLE biblioteca (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    cpf_cnpj VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    telefone VARCHAR(255),
    endereco_id BIGINT,
    data_criacao TIMESTAMP(6),
    ativa BOOLEAN NOT NULL,
    data_atualizacao TIMESTAMP(6),
    CONSTRAINT uk_biblioteca_nome UNIQUE (nome),
    CONSTRAINT uk_biblioteca_cpf_cnpj UNIQUE (cpf_cnpj),
    CONSTRAINT uk_biblioteca_email UNIQUE (email),
    CONSTRAINT uk_biblioteca_endereco UNIQUE (endereco_id),
    CONSTRAINT fk_biblioteca_endereco FOREIGN KEY (endereco_id) REFERENCES endereco (id)
);

CREATE TABLE autor (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    nome_catalogacao VARCHAR(255) NOT NULL,
    ativo BOOLEAN NOT NULL,
    data_criacao TIMESTAMP(6),
    data_atualizacao TIMESTAMP(6),
    CONSTRAINT uk_autor_nome UNIQUE (nome)
);

CREATE TABLE categoria (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    descricao VARCHAR(255),
    ativa BOOLEAN NOT NULL,
    data_criacao TIMESTAMP(6),
    data_atualizacao TIMESTAMP(6),
    CONSTRAINT uk_categoria_nome UNIQUE (nome)
);

CREATE TABLE livro (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo VARCHAR(255) NOT NULL,
    isbn10 VARCHAR(255),
    isbn13 VARCHAR(255) NOT NULL,
    editora VARCHAR(255),
    ano_publicacao INTEGER,
    edicao VARCHAR(255),
    descricao VARCHAR(4000),
    url_imagem_capa VARCHAR(1000),
    ativo BOOLEAN NOT NULL,
    data_criacao TIMESTAMP(6),
    data_atualizacao TIMESTAMP(6),
    CONSTRAINT uk_livro_isbn10 UNIQUE (isbn10),
    CONSTRAINT uk_livro_isbn13 UNIQUE (isbn13)
);

CREATE TABLE autoria (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    livro_id BIGINT NOT NULL,
    autor_id BIGINT NOT NULL,
    ordem INTEGER NOT NULL,
    CONSTRAINT fk_autoria_livro FOREIGN KEY (livro_id) REFERENCES livro (id),
    CONSTRAINT fk_autoria_autor FOREIGN KEY (autor_id) REFERENCES autor (id)
);

CREATE TABLE livro_categoria (
    livro_id BIGINT NOT NULL,
    categoria_id BIGINT NOT NULL,
    CONSTRAINT fk_livro_categoria_livro FOREIGN KEY (livro_id) REFERENCES livro (id),
    CONSTRAINT fk_livro_categoria_categoria FOREIGN KEY (categoria_id) REFERENCES categoria (id)
);

CREATE TABLE acervo (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    biblioteca_id BIGINT NOT NULL,
    livro_id BIGINT NOT NULL,
    quantidade_real INTEGER NOT NULL,
    quantidade_disponivel INTEGER NOT NULL,
    ativo BOOLEAN NOT NULL,
    data_criacao TIMESTAMP(6),
    data_atualizacao TIMESTAMP(6),
    CONSTRAINT fk_acervo_biblioteca FOREIGN KEY (biblioteca_id) REFERENCES biblioteca (id),
    CONSTRAINT fk_acervo_livro FOREIGN KEY (livro_id) REFERENCES livro (id)
);

CREATE TABLE usuario (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    classe_usuario VARCHAR(31) NOT NULL,
    nome_completo VARCHAR(255) NOT NULL,
    data_nascimento DATE,
    login VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    senha_hash VARCHAR(255) NOT NULL,
    tipo_usuario VARCHAR(255) NOT NULL,
    data_criacao TIMESTAMP(6),
    ativo BOOLEAN NOT NULL,
    data_atualizacao TIMESTAMP(6),
    biblioteca_id BIGINT,
    CONSTRAINT uk_usuario_login UNIQUE (login),
    CONSTRAINT uk_usuario_email UNIQUE (email),
    CONSTRAINT fk_usuario_biblioteca FOREIGN KEY (biblioteca_id) REFERENCES biblioteca (id)
);

CREATE TABLE reserva (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    leitor_id BIGINT NOT NULL,
    acervo_id BIGINT NOT NULL,
    data_reserva TIMESTAMP(6),
    status VARCHAR(255),
    CONSTRAINT fk_reserva_leitor FOREIGN KEY (leitor_id) REFERENCES usuario (id),
    CONSTRAINT fk_reserva_acervo FOREIGN KEY (acervo_id) REFERENCES acervo (id)
);
