spring.application.name=consulta-isbn-service
server.port=8081

integracao.brasilapi.url=https://brasilapi.com.br
spring.cloud.openfeign.client.config.brasilApiIsbnClient.connectTimeout=3000
spring.cloud.openfeign.client.config.brasilApiIsbnClient.readTimeout=5000
